openapi: "3.0.0"
info:
  title: ec-site API Document
  version: "0.0.1"
  description: "ec-site API のドキュメントです"
tags:
  - name: items
    description: 商品関連のAPI
paths:
  /items/:
    post:
      summary: "商品作成"
      description: "商品を新規作成します。"
      operationId: "createItem"
      tags:
        - items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemForm"
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDTO"
  /items/{itemId}:
    get:
      summary: "商品取得"
      description: "指定されたIDの商品を１件取得します。"
      tags:
        - items
      operationId: showItem
      parameters:
        - name: itemId
          in: path
          required: true
          description: "詳細を取得する商品のID"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDTO"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
components:
  schemas:
    ItemForm:
      type: object
      properties:
        itemName:
          type: string
          description: "作成される商品の名前"
      required:
        - itemName
    ItemDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "商品ID"
        itemName:
          type: string
          description: "商品名"
      required:
        - id
        - itemName
    ResourceNotFoundError:
      description: "指定したリソースが存在しない"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Resource Not Found"
        detail:
          type: string
          description: "エラーの詳細"
      required:
        - title
        - detail
