openapi: "3.0.0"
info:
  title: ec-site API Document
  version: "0.0.1"
  description: "ec-site API のドキュメントです"
tags:
  - name: items
    description: 商品関連のAPI
  - name: users
    description: ユーザー関連のAPI
paths:
  /items:
    get:
      summary: "商品一覧の取得"
      description: "商品の一覧を取得できます"
      operationId: "listItems"
      tags:
        - items
      parameters:
        - name: limit
          in: query
          required: true
          description: "リソースに含まれるリソースの最大値"
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 10
        - name: offset
          in: query
          required: ture
          description: "オフセット"
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemListDTO"
        '400':
          description: "Bad Resuest"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"

    post:
      summary: "商品の作成"
      description: "商品を新規作成します"
      operationId: "createItem"
      tags:
        - items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemForm"
      responses:
        201:
          description: "Created"
          headers:
            location:
              description: "作成したリソースのURI"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDTO"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
  /items/{itemId}:
    get:
      summary: "商品の取得"
      description: "指定されたIDの商品を１件取得します。"
      tags:
        - items
      operationId: showItem
      parameters:
        - name: itemId
          in: path
          required: true
          description: "詳細を取得する商品のID"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDTO"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
    put:
      summary: "出品した商品の変更"
      description: "指定された商品をリクエストボディの内容で上書きします"
      operationId: "editItem"
      tags:
        - items
      parameters:
        - name: itemId
          in: path
          required: true
          description: "更新する商品のID"
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemForm"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDTO"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
  /users:
    get:
      summary: "ユーザー一覧の取得"
      description: "ユーザーの一覧を取得できます"
      operationId: "listusers"
      tags:
        - users
      parameters:
        - name: limit
          in: query
          required: true
          description: "リソースに含まれるリソースの最大値"
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 10
        - name: offset
          in: query
          required: ture
          description: "オフセット"
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserListDTO"
        '400':
          description: "Bad Resuest"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"

    post:
      summary: "ユーザーの作成"
      description: "ユーザーを新規作成します"
      operationId: "createUser"
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserForm"
      responses:
        201:
          description: "Created"
          headers:
            location:
              description: "作成したリソースのURI"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
  /users/{userId}:
    get:
      summary: "ユーザーの取得"
      description: "指定されたIDのユーザーを１件取得します。"
      tags:
        - users
      operationId: showUser
      parameters:
        - name: userId
          in: path
          required: true
          description: "詳細を取得するユーザーのID"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
    put:
      summary: "登録したユーザーの変更"
      description: "指定されたユーザーをリクエストボディの内容で上書きします"
      operationId: "editUser"
      tags:
        - users
      parameters:
        - name: userId
          in: path
          required: true
          description: "更新するユーザーのID"
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserForm"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
components:
  schemas:
    ItemForm:
      type: object
      properties:
        itemName:
          type: string
          description: "作成される商品の名前"
          maxLength: 20
          minLength: 1
        description:
          type: string
          description: "作成される商品の詳細"
          maxLength: 100
          minLength: 1
        itemimage:
          type: string
          format: binary
          description: "作成される商品の画像"
        company:
          type: string
          description: "作成される販売会社"
          maxLength: 20
          minLength: 1
        price:
          type: int
          description: "作成される商品価格（円）"
          maxLength: 10
          minLength: 1
        stock:
          type: int
          description: "作成される在庫数（個）"
          maxLength: 10
          minLength: 1
      required:
        - itemName
        - description
        - company
        - price
        - stock
    ItemDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "商品ID"
        itemName:
          type: string
          description: "商品名"
        description:
          type: string
          description: "商品概要"
        company:
          type: string
          description: "販売会社"
        price:
          type: integer
          format: int32
          description: "販売価格（円）"
        stock:
          type: integer
          format: int32
          description: "在庫数（個）"
      required:
        - id
        - itemName
        - description
        - company
        - price
        - stock
    UserForm:
      type: object
      properties:
        userName:
          type: string
          description: "作成されるユーザーの名前"
          maxLength: 20
          minLength: 1
        password:
          type: string
          description: "作成されるユーザーのパスワード"
          maxLength: 128
          minLength: 1
        authority:
          type: string
          description: "作成されるユーザー権限"
          maxLength: 20
          minLength: 1
        campany:
          type: string
          description: "作成されるユーザーの所属会社"
          maxLength: 10
          minLength: 1
        address:
          type: string
          description: "作成されるユーザーの住所"
          maxLength: 100
          minLength: 1
        phone:
          type: string
          description: "作成されるユーザーの電話番号"
          maxLength: 255
          minLength: 1
      required:
        - userName
        - password
        - authority
        - campany
        - address
        - phone
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "ユーザーID"
        userName:
          type: string
          description: "ユーザー名"
        password:
          type: string
          description: "パスワード"
        authority:
          type: string
          description: "ユーザー権限"
        campany:
          type: string
          description: "所属会社"
        address:
          type: string
          description: "住所"
        phone:
          type: string
          description: "電話番号"
      required:
        - id
        - password
        - authority
        - campany
        - address
        - phone
    PageDTO:
      description: "ページング情報"
      type: object
      properties:
        limit:
          description: "リクエストされた limit"
          type: integer
          format: int32
        offset:
          description: "リクエストされた offset"
          type: integer
          format: int64
        size:
          description: "取得できた件数"
          type: integer
          format: int32
    ItemListDTO:
      description: "商品のリスト"
      type: object
      properties:
        page:
          $ref: "#/components/schemas/PageDTO"
        results:
          type: array
          items:
            $ref: "#/components/schemas/ItemDTO"
      required:
        - results
    UserListDTO:
      description: "ユーザーのリスト"
      type: object
      properties:
        page:
          $ref: "#/components/schemas/PageDTO"
        results:
          type: array
          items:
            $ref: "#/components/schemas/UserDTO"
      required:
        - results
    ResourceNotFoundError:
      description: "指定したリソースが存在しない"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Resource Not Found"
        detail:
          type: string
          description: "エラーの詳細"
      required:
        - title
        - detail
    BadRequestError:
      description: "リクエストが不正"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Bad Request"
        detail:
          type: string
          description: "エラーの詳細"
          default: "リクエストが不正です。正しいリクエストでリトライしてください"
        invalid-params:
          type: array
          items:
            $ref: "#/components/schemas/InvalidParam"
      required:
        - title
        - detail
        - invalid-params
    InvalidParam:
      description: "不正なリクエストについての詳細"
      type: object
      properties:
        name:
          type: string
          description: "エラーが発生したフィールド名"
        reason:
          type: string
          description: "エラーの理由"
      required:
        - name
        - reason